"""Generate trajectory visualizations from probe NPZ files.

Usage:
    python generate_viz.py                        # all models in outputs/probes/
    python generate_viz.py --model xvla           # single model
    python generate_viz.py --output-dir /path/to/ # custom output directory
    python generate_viz.py --compare              # multi-model comparison plots

NPZ files must exist (generated by run_all.py with trajectory saving enabled).
Plots are saved to outputs/probes/viz/trajectories/.
"""

import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# ── Canonical block positions in scene coordinates ──────────────────────────
RED_BLOCK_DEFAULT = np.array([0.45, -0.03, 0.08])
BLUE_BLOCK_DEFAULT = np.array([0.45, 0.15, 0.08])

# Perturbation offsets (must match perturbation.py)
PERTURBATION_OFFSETS = {
    "shifted_left":    np.array([ 0.0,  0.08, 0.0]),
    "shifted_right":   np.array([ 0.0, -0.08, 0.0]),
    "shifted_forward": np.array([ 0.05, 0.0,  0.0]),
    "shifted_back":    np.array([-0.05, 0.0,  0.0]),
    "raised":          np.array([ 0.0,  0.0,  0.05]),
}

# ── Style ───────────────────────────────────────────────────────────────────
MODEL_COLORS = {
    "xvla":              "#2196F3",
    "pi0":               "#9C27B0",
    "openvla":           "#F44336",
    "openvla_oft":       "#FF9800",
    "cosmos_policy":     "#009688",
    "smolvla":           "#607D8B",
    "groot":             "#8BC34A",
}
MODEL_LABELS = {
    "xvla":              "X-VLA (0.9B)",
    "pi0":               "π₀ (3B)",
    "openvla":           "OpenVLA (7B)",
    "openvla_oft":       "OpenVLA-OFT (7B)",
    "cosmos_policy":     "Cosmos Policy (2B)",
    "smolvla":           "SmolVLA (450M)",
    "groot":             "GR00T N1.6",
}

ALPHA_TRAJ = 0.85
LINEWIDTH = 2.0
MARKER_BLOCK_SIZE = 180
FIGSIZE_SINGLE = (5, 5)
FIGSIZE_COMPARE = (14, 5)
DPI = 150


KNOWN_PROBES = sorted([
    "baseline", "spatial_symmetry", "camera_sensitivity", "view_ablation",
    "counterfactual", "null_action", "attention", "perturbation",
], key=len, reverse=True)  # longest first so multi-word probes match before substrings


def _parse_npz_name(path: Path) -> tuple[str, str, str]:
    """Parse probe_trajectories_{model}_{scene}_{probe}.npz -> (model, scene, probe).

    Uses known probe name list to correctly handle multi-word probe names like
    'spatial_symmetry' and 'camera_sensitivity'.
    """
    stem = path.stem  # e.g. probe_trajectories_cosmos_policy_franka_spatial_symmetry
    prefix = "probe_trajectories_"
    if not stem.startswith(prefix):
        return "unknown", "unknown", "unknown"
    body = stem[len(prefix):]  # e.g. cosmos_policy_franka_spatial_symmetry

    for probe in KNOWN_PROBES:
        suffix = "_" + probe
        if body.endswith(suffix):
            rest = body[: -len(suffix)]  # e.g. cosmos_policy_franka
            rest_parts = rest.split("_")
            scene = rest_parts[-1]
            model = "_".join(rest_parts[:-1])
            return model, scene, probe

    return "unknown", "unknown", "unknown"


def _fmt_model(model: str) -> str:
    return MODEL_LABELS.get(model, model)


def _color(model: str) -> str:
    return MODEL_COLORS.get(model, "#333333")


def _setup_axes(ax, title: str, xlabel="X (m)", ylabel="Y (m)") -> None:
    ax.set_title(title, fontsize=11, fontweight="bold", pad=8)
    ax.set_xlabel(xlabel, fontsize=9)
    ax.set_ylabel(ylabel, fontsize=9)
    ax.set_aspect("equal")
    ax.grid(True, alpha=0.3, linewidth=0.5)
    ax.tick_params(labelsize=8)


def _draw_block(ax, pos_2d: np.ndarray, color: str, label: str, zorder: int = 5) -> None:
    ax.scatter(*pos_2d, c=color, s=MARKER_BLOCK_SIZE, marker="s",
               zorder=zorder, edgecolors="black", linewidth=0.8)
    ax.annotate(label, pos_2d, xytext=(6, 6), textcoords="offset points",
                fontsize=7, zorder=zorder + 1)


def _draw_trajectory(ax, xyz: np.ndarray, color: str, label: str, alpha=ALPHA_TRAJ,
                     lw=LINEWIDTH, linestyle="-", zorder=4) -> None:
    if len(xyz) < 2:
        return
    xy = xyz[:, :2]  # top-down XY
    ax.plot(xy[:, 0], xy[:, 1], color=color, linewidth=lw,
            linestyle=linestyle, alpha=alpha, label=label, zorder=zorder)
    # Start marker
    ax.scatter(xy[0, 0], xy[0, 1], c=color, s=40, marker="o",
               zorder=zorder + 1, alpha=alpha)
    # End arrow
    if len(xy) >= 2:
        dx, dy = xy[-1] - xy[-2]
        ax.annotate("", xy=(xy[-1, 0], xy[-1, 1]),
                    xytext=(xy[-1, 0] - dx * 0.5, xy[-1, 1] - dy * 0.5),
                    arrowprops=dict(arrowstyle="->", color=color,
                                   lw=lw, alpha=alpha),
                    zorder=zorder + 2)


# ── Per-probe plot generators ─────────────────────────────────────────────

def plot_baseline(data: dict, model: str, scene: str, out_dir: Path) -> Path | None:
    key = "trajectory_xyz"
    if key not in data:
        print(f"  [baseline] missing {key}")
        return None

    traj = data[key]
    fig, ax = plt.subplots(1, 1, figsize=FIGSIZE_SINGLE)
    _setup_axes(ax, f"Baseline Trajectory — {_fmt_model(model)}")

    _draw_trajectory(ax, traj, _color(model), "baseline")
    _draw_block(ax, RED_BLOCK_DEFAULT[:2], "red", "red block")
    _draw_block(ax, BLUE_BLOCK_DEFAULT[:2], "dodgerblue", "blue block")

    ax.legend(fontsize=8, loc="best")
    plt.tight_layout()
    out = out_dir / f"baseline_{model}_{scene}.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    return out


def plot_spatial_symmetry(data: dict, model: str, scene: str, out_dir: Path) -> Path | None:
    if "baseline_xyz" not in data or "swapped_xyz" not in data:
        print(f"  [spatial_symmetry] missing trajectories, have: {list(data.keys())}")
        return None

    baseline = data["baseline_xyz"]
    swapped = data["swapped_xyz"]

    fig, axes = plt.subplots(1, 2, figsize=FIGSIZE_COMPARE)
    color = _color(model)

    for ax, (traj, title, red_pos, blue_pos) in zip(
        axes,
        [
            (baseline, "Default positions", RED_BLOCK_DEFAULT[:2], BLUE_BLOCK_DEFAULT[:2]),
            (swapped,  "Swapped positions", BLUE_BLOCK_DEFAULT[:2], RED_BLOCK_DEFAULT[:2]),
        ],
    ):
        _setup_axes(ax, title)
        _draw_trajectory(ax, traj, color, "predicted trajectory")
        _draw_block(ax, red_pos, "red", "red block (target)", zorder=6)
        _draw_block(ax, blue_pos, "dodgerblue", "blue block", zorder=5)

    fig.suptitle(f"Spatial Symmetry Probe — {_fmt_model(model)}", fontsize=12,
                 fontweight="bold", y=1.02)

    # Annotate swap_sensitivity from metrics if we can compute it
    try:
        sens = np.mean(np.abs(swapped[:, :2] - baseline[:, :2]))
        fig.text(0.5, -0.03,
                 f"Mean XY deviation after swap: {sens:.4f} m",
                 ha="center", fontsize=9, color="gray")
    except Exception:
        pass

    plt.tight_layout()
    out = out_dir / f"spatial_symmetry_{model}_{scene}.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    return out


def plot_camera_sensitivity(data: dict, model: str, scene: str, out_dir: Path) -> Path | None:
    if "baseline_xyz" not in data:
        print(f"  [camera_sensitivity] missing baseline_xyz")
        return None

    fig, ax = plt.subplots(1, 1, figsize=FIGSIZE_SINGLE)
    _setup_axes(ax, f"Camera Sensitivity — {_fmt_model(model)}")

    color = _color(model)
    _draw_trajectory(ax, data["baseline_xyz"], color, "baseline", lw=2.5)
    if "mirrored_xyz" in data:
        _draw_trajectory(ax, data["mirrored_xyz"], "orange", "mirrored camera",
                         linestyle="--", lw=2.0)
    if "flipped_xyz" in data:
        _draw_trajectory(ax, data["flipped_xyz"], "crimson", "flipped image",
                         linestyle=":", lw=2.0)

    _draw_block(ax, RED_BLOCK_DEFAULT[:2], "red", "red block")
    _draw_block(ax, BLUE_BLOCK_DEFAULT[:2], "dodgerblue", "blue block")
    ax.legend(fontsize=8, loc="best")
    plt.tight_layout()
    out = out_dir / f"camera_sensitivity_{model}_{scene}.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    return out


def plot_perturbation(data: dict, model: str, scene: str, out_dir: Path) -> Path | None:
    if "baseline_xyz" not in data:
        print(f"  [perturbation] missing baseline_xyz")
        return None

    # Collect perturbation trajectories
    perturb_trajs = {}
    for name in PERTURBATION_OFFSETS:
        key = f"traj_xyz_{name}"
        if key in data:
            perturb_trajs[name] = data[key]

    fig, ax = plt.subplots(1, 1, figsize=FIGSIZE_SINGLE)
    _setup_axes(ax, f"Perturbation Probe — {_fmt_model(model)}")

    color = _color(model)
    _draw_trajectory(ax, data["baseline_xyz"], color, "baseline (default pos)",
                     lw=2.5, alpha=0.95)

    perturb_colors = ["#E91E63", "#9C27B0", "#FF5722", "#607D8B", "#795548"]
    for (name, traj), pc in zip(perturb_trajs.items(), perturb_colors):
        block_pos = RED_BLOCK_DEFAULT[:2] + PERTURBATION_OFFSETS[name][:2]
        _draw_trajectory(ax, traj, pc, name.replace("_", " "),
                         linestyle="--", lw=1.5, alpha=0.75)
        ax.scatter(*block_pos, c=pc, s=80, marker="^", zorder=6, alpha=0.85)

    # Default red block position
    _draw_block(ax, RED_BLOCK_DEFAULT[:2], "red", "default pos", zorder=7)

    if not perturb_trajs:
        ax.text(0.5, 0.5,
                "No perturbation trajectories saved.\nRe-run probes with updated run_all.py.",
                transform=ax.transAxes, ha="center", va="center",
                fontsize=9, color="gray",
                bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.5))

    ax.legend(fontsize=7, loc="best", ncol=2)
    plt.tight_layout()
    out = out_dir / f"perturbation_{model}_{scene}.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    return out


def plot_model_summary(all_data: dict[str, dict], scene: str, out_dir: Path) -> Path | None:
    """Multi-model baseline trajectory overlay for a single scene."""
    models_with_baseline = [
        m for m, probes in all_data.items()
        if "baseline" in probes and "trajectory_xyz" in probes["baseline"]
    ]
    if not models_with_baseline:
        print("  [summary] no baseline trajectory data for any model")
        return None

    fig, ax = plt.subplots(1, 1, figsize=(7, 6))
    _setup_axes(ax, f"Baseline Trajectories — All Models ({scene})")

    for model in models_with_baseline:
        traj = all_data[model]["baseline"]["trajectory_xyz"]
        _draw_trajectory(ax, traj, _color(model), _fmt_model(model))

    _draw_block(ax, RED_BLOCK_DEFAULT[:2], "red", "red block (target)", zorder=9)
    _draw_block(ax, BLUE_BLOCK_DEFAULT[:2], "dodgerblue", "blue block", zorder=8)

    ax.legend(fontsize=8, loc="best")
    plt.tight_layout()
    out = out_dir / f"all_models_baseline_{scene}.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    return out


PROBE_PLOTTERS = {
    "baseline":            plot_baseline,
    "spatial_symmetry":    plot_spatial_symmetry,
    "camera_sensitivity":  plot_camera_sensitivity,
    "perturbation":        plot_perturbation,
}


# ── Main ─────────────────────────────────────────────────────────────────────

def load_npz_data(npz_dir: Path, model_filter: str | None = None) -> dict:
    """Load all NPZ files. Returns: {model: {scene: {probe: {key: array}}}}"""
    result = {}
    for npz_file in sorted(npz_dir.glob("probe_trajectories_*.npz")):
        model, scene, probe = _parse_npz_name(npz_file)
        if model_filter and model != model_filter:
            continue
        data = np.load(npz_file, allow_pickle=False)
        result.setdefault(model, {}).setdefault(scene, {})[probe] = dict(data)
        print(f"  Loaded {npz_file.name}: {list(data.keys())}")
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate trajectory plots from probe NPZ files")
    parser.add_argument("--model", help="Filter to a specific model")
    parser.add_argument(
        "--npz-dir", default="outputs/probes",
        help="Directory containing probe_trajectories_*.npz files",
    )
    parser.add_argument(
        "--output-dir", default="outputs/probes/viz/trajectories",
        help="Directory to save PNG plots",
    )
    parser.add_argument(
        "--compare", action="store_true",
        help="Generate multi-model comparison plots",
    )
    args = parser.parse_args()

    npz_dir = Path(args.npz_dir)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading NPZ files from {npz_dir}...")
    all_data = load_npz_data(npz_dir, model_filter=args.model)

    if not all_data:
        print(
            "\nNo NPZ trajectory files found. Run probes with the updated run_all.py first.\n"
            "Each model needs to be re-run; NPZ files are saved alongside JSON results."
        )
        return

    generated = []
    for model, scenes in sorted(all_data.items()):
        for scene, probes in sorted(scenes.items()):
            print(f"\n{model} / {scene}:")
            for probe_name, data in sorted(probes.items()):
                plotter = PROBE_PLOTTERS.get(probe_name)
                if plotter is None:
                    continue
                out = plotter(data, model, scene, out_dir)
                if out:
                    generated.append(out)
                    print(f"  -> {out.name}")

    if args.compare:
        print("\nGenerating multi-model comparison plots...")
        # Collect by scene
        scenes = set()
        for model_scenes in all_data.values():
            scenes |= set(model_scenes.keys())
        for scene in scenes:
            scene_data = {
                m: probes[scene]
                for m, probes in all_data.items()
                if scene in probes
            }
            out = plot_model_summary(scene_data, scene, out_dir)
            if out:
                generated.append(out)
                print(f"  -> {out.name}")

    print(f"\nGenerated {len(generated)} plots in {out_dir}/")
    for p in generated:
        print(f"  {p}")


if __name__ == "__main__":
    main()
